# Generated by Django 4.2.1 on 2023-05-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_alter_tarefa_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_de_execucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data de execução'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.BooleanField(default=False, verbose_name='finalizado'),
        ),
    ]
